DOMAIN = "stekker"
DEFAULT_BIDDING_ZONE = "BE"  # Belgium
BIDDING_ZONES_MAP = {
    "BE": "Belgium",
    "NL": "Netherlands",
    "DE-LU": "Germany & Luxembourg",
    "FR": "France",
    "CH": "Switzerland",
    "SE4": "Sweden SE4",
    "SE3": "Sweden SE3",
    "SE1": "Sweden SE1",
    "DK1": "Denmark DK1",
    "DK2": "Denmark DK2",
    "FI": "Finland",
    "NO1": "Norway NO1",
    "NO2": "Norway NO2",
    "NO3": "Norway NO3",
    "NO4": "Norway NO4",
    "NO5": "Norway NO5",
    "LV": "Latvia",
    "LT": "Lithuania",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RS": "Serbia",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "HU": "Hungary",
    "AT": "Austria",
    "CZ": "Czech Republic",
    "HR": "Croatia",
    "EE": "Estonia"
}
